### ISSUE TITLE
Deploy error on modulus.io

### ISSUE THREAD

**Issue by stevenhornung** [gadicc/meteor-phantomjs#11]
When deploying with this package on Modulus.io I get the following error:

module.js:340
    throw err;
          ^
Error: Cannot find module './util'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/mnt/data/1/node_modules/adm-zip/zipEntry.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Then this constant error after startup:

Error: Can't find npm module 'phantomjs-sun'. Did you forget to call 'Npm.depends' in package.js within the 'gadicohen_phantomjs' package?
    at Object.Npm.require (/mnt/data/1/programs/server/boot.js:113:17)
    at Package (packages/gadicohen:phantomjs/phantom.js:1)
    at /mnt/data/1/programs/server/packages/gadicohen_phantomjs.js:19:4
    at /mnt/data/1/programs/server/packages/gadicohen_phantomjs.js:26:3
    at /mnt/data/1/programs/server/boot.js:168:10
    at Array.forEach (native)
    at Function._.each._.forEach (/mnt/data/1/node_modules/underscore/underscore.js:79:11)
    at /mnt/data/1/programs/server/boot.js:82:5

**Comment by stevenhornung** [comment]
Just needed to add phantomjs-sun to packages.json so it actually pulled in phantomjs-sun
