### ISSUE TITLE
spiderable: phantomjs failed: { [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }

### ISSUE THREAD

**Issue by meichenblatt** [gadicc/meteor-phantomjs#13]
Hi Gadi,

I was consistently getting this error and I was sure it was something on my side so create a clean app and only added spiderable and gadicohen:phantomjs. This error still showed up. 

This is the full error from my development app:

spiderable: phantomjs failed: { [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }
stderr:
Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
at [object Object].RouteController.lookupOption (packages/iron:router/lib/route_controller.js:66:1)
at new Controller.extend.constructor (packages/iron:router/lib/route_controller.js:26:1)
at [object Object].ctor (packages/iron:core/lib/iron_core.js:88:1)
at Function.Router.createController (packages/iron:router/lib/router.js:201:1)
at Function.Router.dispatch (packages/iron:router/lib/router_server.js:39:1)
at Object.router (packages/iron:router/lib/router.js:15:1)

Thank you!

**Comment by meichenblatt** [comment]
anything?

**Comment by m52go** [comment]
I'm getting something similar...

```
I20150824-15:00:50.374(-4)? spiderable: phantomjs not installed. Download and install from http://phantomjs.org/
W20150824-15:00:50.377(-4)? (STDERR) Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
```

**Comment by txs** [comment]
Me too! I got the spawn error! How to solve it!

**Comment by kenshinman** [comment]
Hi, has anyone been able to solve this? I have the same problem here
